version: "3.8"

x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: ${FLUENT_BIT_ADDRESS}:24224

services:
  followers_service:
    image: followers_service
    container_name: followers_service
    build:
      context: .
      dockerfile: ./Followers_microservice/Dockerfile
    restart: on-failure
    env_file:
      - .env
    environment:
      FOLLOWERS_SERVICE_PORT:   ${ENV_FOLLOWERS_SERVICE_PORT}
      NEO4J_DATABASE:           ${ENV_NEO4J_DATABASE}
      FOLLOWERS_DB_HOST:        ${ENV_FOLLOWERS_DB_HOST}
      NEO4J_USER:               ${ENV_NEO4J_USER}
      NEO4J_PASSWORD:           ${ENV_NEO4J_PASSWORD}
      NEO4J_VERSION:            ${ENV_NEO4J_VERSION}
      USERS_SERVICE_HOST:       ${ENV_USERS_SERVICE_HOST}
      USERS_PORT:               ${ENV_USERS_PORT}
      NATS_HOST:                ${ENV_NATS_HOST}
      NATS_PORT:                ${ENV_NATS_PORT}
      NATS_USER:                ${ENV_NATS_USER}
      NATS_PASS:                ${ENV_NATS_PASS}
      BLOCK_COMMAND_SUBJECT:    ${ENV_BLOCK_COMMAND_SUBJECT}
      BLOCK_REPLY_SUBJECT:      ${ENV_BLOCK_REPLY_SUBJECT}
      UNBLOCK_COMMAND_SUBJECT:  ${ENV_UNBLOCK_COMMAND_SUBJECT}
      UNBLOCK_REPLY_SUBJECT:    ${ENV_UNBLOCK_REPLY_SUBJECT}
      JAEGER_AGENT_HOST:        ${ENV_JAEGER_AGENT_HOST}
      JAEGER_AGENT_PORT:        ${ENV_JAEGER_AGENT_PORT}
      JAEGER_SAMPLER_TYPE:      ${ENV_JAEGER_SAMPLER_TYPE}
      JAEGER_SAMPLER_PARAM:     ${ENV_JAEGER_SAMPLER_PARAM}
    logging: *fluent-bit
    depends_on:
      - followers_db
      - nats
    networks:
      - network
      - monitoring

  followers_db:
    image: neo4j
    container_name: followers_db
    restart: on-failure
    environment:
      NEO4J_AUTH: none
    logging: *fluent-bit
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - network
      - monitoring

  posts_service:
    image: posts_service
    container_name: posts_service
    build:
      context: .
      dockerfile: ./Posts_microservice/Dockerfile
    restart: on-failure
    environment:
      POSTS_SERVICE_PORT: ${ENV_POSTS_SERVICE_PORT}
      POSTS_DB_HOST: ${ENV_POSTS_DB_HOST}
      POSTS_DB_PORT: ${ENV_POSTS_DB_PORT}
      FOLLOWERS_SERVICE_HOST:   ${ENV_FOLLOWERS_SERVICE_HOST}
      FOLLOWERS_SERVICE_PORT:   ${ENV_FOLLOWERS_SERVICE_PORT}
      USERS_SERVICE_HOST:       ${ENV_USERS_SERVICE_HOST}
      USERS_PORT:               ${ENV_USERS_PORT}
      NOTIFICATIONS_HOST:       ${ENV_NOTIFICATIONS_HOST}
      NOTIFICATIONS_PORT:       ${ENV_NOTIFICATIONS_PORT}
      JAEGER_AGENT_HOST:        ${ENV_JAEGER_AGENT_HOST}
      JAEGER_AGENT_PORT:        ${ENV_JAEGER_AGENT_PORT}
      JAEGER_SAMPLER_TYPE:      ${ENV_JAEGER_SAMPLER_TYPE}
      JAEGER_SAMPLER_PARAM:     ${ENV_JAEGER_SAMPLER_PARAM}
    logging: *fluent-bit
    depends_on:
      - posts_db
    networks:
      - network
      - monitoring

  posts_db:
    image: mongo
    container_name: posts_db
    logging: *fluent-bit
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - network
      - monitoring
      
  job_offers_service:
    image: job_offers_service
    container_name: job_offers_service
    build:
        context: .
        dockerfile: ./Job_Offers_microservice/Dockerfile
    restart: on-failure
    environment: 
        JOB_OFFERS_SERVICE_PORT:    ${ENV_JOB_OFFERS_SERVICE_PORT}
        JOB_OFFERS_DB_HOST:         ${ENV_JOB_OFFERS_DB_HOST}
        JOB_OFFERS_DB_PORT:         ${ENV_JOB_OFFERS_DB_PORT}
        USERS_SERVICE_HOST:         ${ENV_USERS_SERVICE_HOST}
        USERS_PORT:                 ${ENV_USERS_PORT}
        JAEGER_AGENT_HOST:        ${ENV_JAEGER_AGENT_HOST}
        JAEGER_AGENT_PORT:        ${ENV_JAEGER_AGENT_PORT}
        JAEGER_SAMPLER_TYPE:      ${ENV_JAEGER_SAMPLER_TYPE}
        JAEGER_SAMPLER_PARAM:     ${ENV_JAEGER_SAMPLER_PARAM}
    logging: *fluent-bit
    depends_on:
        - job_offers_db
    networks:
        - network
        - monitoring
        
  job_offers_db:
    image: mongo
    container_name: job_offers_db
    logging: *fluent-bit
    restart: on-failure
    networks:
      - network
      - monitoring
     

  chat_service:
    image: chat_service
    container_name: chat_service
    build:
        context: .
        dockerfile: ./Chat_microservice/Dockerfile
    restart: on-failure
    environment: 
        CHAT_PORT:                  ${ENV_CHAT_PORT}
        CHAT_DB_HOST:               ${ENV_CHAT_DB_HOST}
        CHAT_DB_PORT:               ${ENV_CHAT_DB_PORT}
        NOTIFICATIONS_HOST:         ${ENV_NOTIFICATIONS_HOST}
        NOTIFICATIONS_HOST:         ${ENV_NOTIFICATIONS_HOST}
        NOTIFICATIONS_PORT:         ${ENV_NOTIFICATIONS_PORT}
        NATS_HOST:                  ${ENV_NATS_HOST}
        NATS_PORT:                  ${ENV_NATS_PORT}
        NATS_USER:                  ${ENV_NATS_USER}
        NATS_PASS:                  ${ENV_NATS_PASS}
        BLOCK_COMMAND_SUBJECT:      ${ENV_BLOCK_COMMAND_SUBJECT}
        BLOCK_REPLY_SUBJECT:        ${ENV_BLOCK_REPLY_SUBJECT}
        UNBLOCK_COMMAND_SUBJECT:    ${ENV_UNBLOCK_COMMAND_SUBJECT}
        UNBLOCK_REPLY_SUBJECT:      ${ENV_UNBLOCK_REPLY_SUBJECT}
        JAEGER_AGENT_HOST:          ${ENV_JAEGER_AGENT_HOST}
        JAEGER_AGENT_PORT:          ${ENV_JAEGER_AGENT_PORT}
        JAEGER_SAMPLER_TYPE:        ${ENV_JAEGER_SAMPLER_TYPE}
        JAEGER_SAMPLER_PARAM:       ${ENV_JAEGER_SAMPLER_PARAM}
    logging: *fluent-bit
    depends_on: 
        - chat_db
        - nats
    networks:
        - network
        - monitoring
     
  chat_db:
    image: mongo
    container_name: chat_db
    restart: on-failure
    networks:
      - network
      - monitoring
     
  users_service:
    image: users_service
    container_name: users_service
    build:
        context: .
        dockerfile: ./JavaMicroservices/User-microservice/Dockerfile
    restart: on-failure
    environment:
        USERS_PORT: ${ENV_USERS_PORT}
        USERS_DB_HOST: ${ENV_USERS_DB_HOST}
        USERS_DB_PORT: ${ENV_USERS_DB_PORT}
        JAEGER_AGENT_HOST:        ${ENV_JAEGER_AGENT_HOST}
        JAEGER_AGENT_PORT:        ${ENV_JAEGER_AGENT_PORT}
        JAEGER_SAMPLER_TYPE:      ${ENV_JAEGER_SAMPLER_TYPE}
        JAEGER_SAMPLER_PARAM:     ${ENV_JAEGER_SAMPLER_PARAM}
    logging: *fluent-bit
    depends_on:
        - users_db
        - jaeger
    networks:
      - network
      - monitoring
        
        
  users_db:
    image: mongo
    container_name: users_db
    logging: *fluent-bit
    restart: on-failure
    networks:
      - network
      - monitoring
     
  notifications_service:
    image: notifications_service
    container_name: notifications_service
    build:
        context: .
        dockerfile: ./JavaMicroservices/Notification-microservice/Dockerfile
    restart: on-failure
    environment:
        NOTIFICATIONS_PORT:     ${ENV_NOTIFICATIONS_PORT}
        NOTIFICATIONS_DB_HOST:  ${ENV_NOTIFICATIONS_DB_HOST}
        NOTIFICATIONS_DB_PORT:  ${ENV_NOTIFICATIONS_DB_PORT}
        JAEGER_AGENT_HOST:      ${ENV_JAEGER_AGENT_HOST}
        JAEGER_AGENT_PORT:      ${ENV_JAEGER_AGENT_PORT}
        JAEGER_SAMPLER_TYPE:    ${ENV_JAEGER_SAMPLER_TYPE}
        JAEGER_SAMPLER_PARAM:   ${ENV_JAEGER_SAMPLER_PARAM}
    logging: *fluent-bit
    depends_on:
        - notifications_db
        - jaeger
    networks:
      - network
      - monitoring
      
  notifications_db:
    image: mongo
    container_name: notifications_db
    logging: *fluent-bit
    restart: on-failure
    networks:
      - network
      - monitoring
  
  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${ENV_GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${ENV_GATEWAY_PORT}
      FOLLOWERS_SERVICE_HOST:   ${ENV_FOLLOWERS_SERVICE_HOST}
      FOLLOWERS_SERVICE_PORT:   ${ENV_FOLLOWERS_SERVICE_PORT}
      POSTS_SERVICE_HOST:       ${ENV_POSTS_SERVICE_HOST}
      POSTS_SERVICE_PORT:       ${ENV_POSTS_SERVICE_PORT}
      USERS_SERVICE_HOST:       ${ENV_USERS_SERVICE_HOST}
      USERS_PORT:               ${ENV_USERS_PORT}
      JOB_OFFERS_SERVICE_HOST:  ${ENV_JOB_OFFERS_SERVICE_HOST}
      JOB_OFFERS_SERVICE_PORT:  ${ENV_JOB_OFFERS_SERVICE_PORT}
      CHAT_HOST:                ${ENV_CHAT_HOST}
      CHAT_PORT:                ${ENV_CHAT_PORT}
      JAEGER_AGENT_HOST:        ${ENV_JAEGER_AGENT_HOST}
      JAEGER_AGENT_PORT:        ${ENV_JAEGER_AGENT_PORT}
      JAEGER_SAMPLER_TYPE:      ${ENV_JAEGER_SAMPLER_TYPE}
      JAEGER_SAMPLER_PARAM:     ${ENV_JAEGER_SAMPLER_PARAM}
    logging: *fluent-bit
    networks:
      - network
      - monitoring

  agent_application:
    image: agent_application
    container_name: agent_application
    build:
        context: .
        dockerfile: ./AgentApplication/Dockerfile
    restart: on-failure
    ports:
      - 9000:9000
    environment:
      AGENT_APPLICATION_DB_CONNECTION_STRING: ${ENV_AGENT_APPLICATION_DB_CONNECTION_STRING}
      GATEWAY_PORT: ${ENV_GATEWAY_PORT}
      GATEWAY_HOST: ${ENV_GATEWAY_HOST}
    logging: *fluent-bit
    depends_on:
        - agent_app_db
    networks:
      - network
      - monitoring
        
  agent_app_db:
    image: postgres
    container_name: agent_app_db
    restart: on-failure
    environment:
        POSTGRES_PASSWORD: "root"
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "AgentApplication"
    logging: *fluent-bit
    networks:
      - network
      - monitoring

  dislinkt_frontend:
    image: dislinkt_frontend
    container_name: dislinkt_frontend
    build:
        context: .
        dockerfile: ./dislinkt-frontend/Dockerfile
        args:
          REACT_APP_BASEURL_DISLINKT: ${REACT_APP_BASE_URL_DISLINKT}
    logging: *fluent-bit
    restart: on-failure
    ports:
      - 3002:3000
    networks:
      - network
      - monitoring

  agent_frontend:
    image: agent_frontend
    container_name: agent_frontend
    build:
        context: .
        dockerfile: ./agent-app-frontend/Dockerfile
        args:
          REACT_APP_BASEURL_AGENT: ${REACT_APP_BASE_URL_AGENT}
    logging: *fluent-bit
    restart: on-failure
    ports:
      - 3001:3000
    networks:
      - network
      - monitoring

  nats:
    image: nats
    container_name: nats
    logging: *fluent-bit
    restart: on-failure
    networks:
      - network
      - monitoring
  
networks:
  network:
    driver: bridge
  monitoring:
    external: true

volumes:
  grafana:
    name: grafana
  prometheus:
    name: prometheus